language: minimal
dist: trusty
branches:
  only:
    - master
    - develop
    - fork

matrix:
  include:
    - name: Shellcheck static analysis
      env: SHELLCHECK=1 SETUP_SCRIPT=/dev/null
    - name: Normal method of specifying Python version
      language: python
    - name: Use PYENV_VERSION with CPython, specific major.minor.change version
      env: PYENV_VERSION=3.6.1 PYENV_VERSION_STRING='Python 3.6.1'
    - name: Use PYENV_VERSION with CPython which Travis has installed already
      env: PYENV_VERSION=2.7.14 PYENV_VERSION_STRING='Python 2.7.14'
    - name: Use PYENV_VERSION with PyPy
      env: PYENV_VERSION=pypy2.7-5.8.0 PYENV_VERSION_STRING='PyPy 5.8.0'
    - name: Use PYENV_VERSION with PyPy and custom options
      env: PYENV_VERSION=pypy3.5-portable-5.8.0 PYENV_VERSION_STRING='PyPy 5.8.0-beta0' PYENV_ROOT=$HOME/.pyenv-pypy PYENV_RELEASE=v1.1.2 PYENV_CACHE_PATH=$HOME/.pyenv-pypy-cache
    - name: Legacy setup-pypy.sh
      env: PYPY_VERSION=5.7.1 SETUP_SCRIPT=setup-pypy.sh
    - name: macOS
      os: osx
      env: PYENV_VERSION=3.6.1 PYENV_VERSION_STRING='Python 3.6.1'
    # macOS Framework Build
    # Useful for PyInstaller
    # Example issue: https://github.com/pyenv/pyenv/issues/443
    - name: macOS Framework Build
      os: osx
      env: PYENV_VERSION=3.6.1 PYENV_VERSION_STRING='Python 3.6.1' PYTHON_CONFIGURE_OPTS="--enable-framework"
    - name: Multiple pythons
      env: PYTHON_VERSIONS="3.6.1 2.7.14 pypy2.7-5.8.0 pypy3.5-5.8.0" SETUP_SCRIPT=multi-pyenv.sh
    - name: Multiple newer pythons
      dist: xenial
      env: PYTHON_VERSIONS="3.7.2 2.7.15 pypy2.7-7.0.0 pypy3.6-7.0.0" SETUP_SCRIPT=multi-pyenv.sh
    - name: Multiple pythons on osx
      os: osx
      env: PYTHON_VERSIONS="3.6.1 2.7.14 pypy2.7-5.8.0" SETUP_SCRIPT=multi-pyenv.sh
    - name: Multiple newer pythons on osx
      os: osx
      env: PYTHON_VERSIONS="3.7.2 2.7.15 pypy2.7-7.0.0 pypy3.6-7.0.0" SETUP_SCRIPT=multi-pyenv.sh

cache:
  - pip
  - directories:
      - "${PYENV_CACHE_PATH:-$HOME/.pyenv_cache}"

script:
  - source "${SETUP_SCRIPT:-setup-pyenv.sh}"
  - pyenv --version
  - pyenv versions
  - python --version
  - if [[ -n "$SHELLCHECK" ]]; then shellcheck *.sh; fi

deploy:
  provider: releases
  api_key:
    secure: J7ho70ZD6vMvug30vjDBDy8+AiSssGeCrOwXY2WD9aGzF1u3+n8yJPL5AgGQrEkmgWKeI+hj9fLdc32oQ0msRJe2NSzqH6pnsaWfOm5dnWJCq7bkuaGaHughCl/AEu5Ob6bf/YNcvEvcDaPRH2QGOsWuCvobON2FykhnMXpwY7N38rtnNhw1riJ8/oMmANGt9VgpwFYPlyRs2KWB3rSof4gx4/WzxVXe005bwviJr1wQYSDKPPvFbKwvYLRpzZ37UvpvfT7ut2g8gXC9PJZueXLXmO93df7quuuFWlVvrYDtq3Yohv9iH0fIMvMu+gKPOT/WKvkh9B1JtJFcy7d43NBC6DJFWTTR14DdVJT7sBMwVoUR4QBgEUHqkyai0UIrALKP+Ubh7YKVE5eweM0luV2o1Lk5WBNOZgpNXjAGrVR3Cr24X0/6kj+n4GbWotYudVPL7cT6k431M6lG545vLoJ29W+GoHIzLe7BFnxDbvEHRwK2OvE318MCNjIg3wh3kat/jf/+6QPH9+LJpp9dfgpiiY4oimHGxeQWAKaZxH3dcBydADHxsXKkmCspdWzS3vQBEHeRg0SMY54fPD3KZA/GlSbJ45JsVfYGyz2RdyG+iGitvLPjjxm7aIlEcY0PAC5kWo3KtJ4mLNT6OgMmWzkQIj3Ueb33BOOrGGijIiI=
  file:
    - setup-pyenv.sh
    - multi-pyenv.sh
  on:
    tags: true

notifications:
  slack:
    secure: OWRZitmcvuIKr/FdGtZOipdeFBifTDbay7fZMjgnTp4qKE1mQaz/LfjTEmLuRxDPUXhC3nJoTYQt0W9wvEKoskQjCKENp89+6Rtu+twS0tn0WDmfvphfzeOGmxWHYBk7q3+kLxojhHGT2JTi54NOaT2qTzpjxLn093zQmaz0s3XSuGmrwSH2y+exZjSYnfNQybZQ+eLK5z/uHHW7K771k3G40i7/c2zvfJOZqKO/DNvdwgaXsLfAXfWRlVmioaZDg6hKDQIIf3ez+ZJir7zoqR0mj6+z4ZMDOW6NZkR94dKJCC0cAwd9QRkqEPtwqv6pe0eWYlzeXtYks7aRlgkzJyEk1mjeLnGD9m2RbADSLmuhqYsePiuxS7814NsH01O1iuaGd9geeQSBZUg48mvvLfitgcFe148MnZC7woYd7ozGzb/v2341gHnxZjKj5VAui9T5keRA8xz+Zryam1MDqCx1Z4srpqFiwmtqbzt4nBx1KSVYKTBGF8nRivD5/R7H4WxTu+zTVxIseQm1zjI4o3c/Lak1x1gRobZ5ARe/9tK1334llKty9t58bVC9XmMnzZoi4R+YlNeyFEG5PegbG8EIktyLEyvFle/2oJAnrVgXqnxoiQFq9McB5AOPaDcCtQkyaFZHa6GA2Fb4BNAJkdhPWC8/OZ/MhzEruJzwd3Y=
